project_id = "ritpcnfqknqlwednskvv"

[functions.time-clock-employees]
verify_jwt = false

[functions.time-clock-punch]
verify_jwt = false

[functions.meeting-public]
verify_jwt = false

[functions.send-meeting-minutes]
verify_jwt = false

[functions.send-warning-email]
verify_jwt = false

[functions.vacation-public]
verify_jwt = false

[functions.send-vacation-email]
verify_jwt = false

[functions.attendance-dashboard]
verify_jwt = false

[functions.employee-portal]
verify_jwt = false

[functions.vehicle-inspection]
verify_jwt = false

[functions.gestaoclick-purchases]
verify_jwt = false
